// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS8MbwR2JjeX64O3NfWzriTdMQEHJvqaE',
    appId: '1:248136435209:web:9ff67a6d674b43da945ad8',
    messagingSenderId: '248136435209',
    projectId: 'auto-repair-app1',
    authDomain: 'auto-repair-app1.firebaseapp.com',
    storageBucket: 'auto-repair-app1.firebasestorage.app',
    measurementId: 'G-7SF9GDX7L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtbSqBFzeWE79AS7DyJRYWoys1UFgHKbw',
    appId: '1:248136435209:android:1460cd401ad1ab43945ad8',
    messagingSenderId: '248136435209',
    projectId: 'auto-repair-app1',
    storageBucket: 'auto-repair-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKZcR8pKQOonn5p-3VF2tY4dSkXYuo3sY',
    appId: '1:248136435209:ios:e2ea5fb7091f3470945ad8',
    messagingSenderId: '248136435209',
    projectId: 'auto-repair-app1',
    storageBucket: 'auto-repair-app1.firebasestorage.app',
    iosBundleId: 'com.example.adminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKZcR8pKQOonn5p-3VF2tY4dSkXYuo3sY',
    appId: '1:248136435209:ios:e2ea5fb7091f3470945ad8',
    messagingSenderId: '248136435209',
    projectId: 'auto-repair-app1',
    storageBucket: 'auto-repair-app1.firebasestorage.app',
    iosBundleId: 'com.example.adminWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS8MbwR2JjeX64O3NfWzriTdMQEHJvqaE',
    appId: '1:248136435209:web:3176a4da3de061f3945ad8',
    messagingSenderId: '248136435209',
    projectId: 'auto-repair-app1',
    authDomain: 'auto-repair-app1.firebaseapp.com',
    storageBucket: 'auto-repair-app1.firebasestorage.app',
    measurementId: 'G-6JMYTLMYG0',
  );
}
